// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"
)

const closeActionItem = `-- name: CloseActionItem :exec
UPDATE action_items SET closed_at = ?, closing_note = ? WHERE id = ? AND closed_at = ''
`

type CloseActionItemParams struct {
	ClosedAt    string
	ClosingNote string
	ID          int64
}

func (q *Queries) CloseActionItem(ctx context.Context, arg CloseActionItemParams) error {
	_, err := q.db.ExecContext(ctx, closeActionItem, arg.ClosedAt, arg.ClosingNote, arg.ID)
	return err
}

const createActionItem = `-- name: CreateActionItem :one
INSERT INTO action_items (report_definition_id, publication_id, comment_id, text, owner_id, due_date, created_by, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, report_definition_id, publication_id, comment_id, text, owner_id, due_date, created_by, created_at, closed_at, closing_note
`

type CreateActionItemParams struct {
	ReportDefinitionID int64
	PublicationID      int64
	CommentID          int64
	Text               string
	OwnerID            int64
	DueDate            string
	CreatedBy          int64
	CreatedAt          string
}

func (q *Queries) CreateActionItem(ctx context.Context, arg CreateActionItemParams) (ActionItem, error) {
	row := q.db.QueryRowContext(ctx, createActionItem,
		arg.ReportDefinitionID,
		arg.PublicationID,
		arg.CommentID,
		arg.Text,
		arg.OwnerID,
		arg.DueDate,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var i ActionItem
	err := row.Scan(
		&i.ID,
		&i.ReportDefinitionID,
		&i.PublicationID,
		&i.CommentID,
		&i.Text,
		&i.OwnerID,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ClosedAt,
		&i.ClosingNote,
	)
	return i, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (publication_id, goal_id, parent_id, author_id, body, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, publication_id, goal_id, parent_id, author_id, body, created_at
`

type CreateCommentParams struct {
	PublicationID int64
	GoalID        int64
	ParentID      int64
	AuthorID      int64
	Body          string
	CreatedAt     string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.PublicationID,
		arg.GoalID,
		arg.ParentID,
		arg.AuthorID,
		arg.Body,
		arg.CreatedAt,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PublicationID,
		&i.GoalID,
		&i.ParentID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const getActionItem = `-- name: GetActionItem :one
SELECT id, report_definition_id, publication_id, comment_id, text, owner_id, due_date, created_by, created_at, closed_at, closing_note FROM action_items WHERE id = ? LIMIT 1
`

func (q *Queries) GetActionItem(ctx context.Context, id int64) (ActionItem, error) {
	row := q.db.QueryRowContext(ctx, getActionItem, id)
	var i ActionItem
	err := row.Scan(
		&i.ID,
		&i.ReportDefinitionID,
		&i.PublicationID,
		&i.CommentID,
		&i.Text,
		&i.OwnerID,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ClosedAt,
		&i.ClosingNote,
	)
	return i, err
}

const getComment = `-- name: GetComment :one
SELECT comments.id, comments.publication_id, comments.goal_id, comments.parent_id, comments.author_id, comments.body, comments.created_at, accounts.id, accounts.email, accounts.is_admin, accounts.created_at, accounts.departed
FROM comments
JOIN accounts ON accounts.id = comments.author_id
WHERE comments.id = ?
LIMIT 1
`

type GetCommentRow struct {
	Comment Comment
	Account Account
}

func (q *Queries) GetComment(ctx context.Context, id int64) (GetCommentRow, error) {
	row := q.db.QueryRowContext(ctx, getComment, id)
	var i GetCommentRow
	err := row.Scan(
		&i.Comment.ID,
		&i.Comment.PublicationID,
		&i.Comment.GoalID,
		&i.Comment.ParentID,
		&i.Comment.AuthorID,
		&i.Comment.Body,
		&i.Comment.CreatedAt,
		&i.Account.ID,
		&i.Account.Email,
		&i.Account.IsAdmin,
		&i.Account.CreatedAt,
		&i.Account.Departed,
	)
	return i, err
}

const listOpenActionItems = `-- name: ListOpenActionItems :many
SELECT id, report_definition_id, publication_id, comment_id, text, owner_id, due_date, created_by, created_at, closed_at, closing_note FROM action_items
WHERE report_definition_id = ? AND closed_at = ''
ORDER BY due_date, id
`

// A Report Definition's open Action Items, soonest due first.
func (q *Queries) ListOpenActionItems(ctx context.Context, reportDefinitionID int64) ([]ActionItem, error) {
	rows, err := q.db.QueryContext(ctx, listOpenActionItems, reportDefinitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActionItem
	for rows.Next() {
		var i ActionItem
		if err := rows.Scan(
			&i.ID,
			&i.ReportDefinitionID,
			&i.PublicationID,
			&i.CommentID,
			&i.Text,
			&i.OwnerID,
			&i.DueDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ClosedAt,
			&i.ClosingNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicationActionItems = `-- name: ListPublicationActionItems :many
SELECT id, report_definition_id, publication_id, comment_id, text, owner_id, due_date, created_by, created_at, closed_at, closing_note FROM action_items
WHERE publication_id = ?
ORDER BY id
`

// The Action Items raised on one publication, in the order they were raised.
func (q *Queries) ListPublicationActionItems(ctx context.Context, publicationID int64) ([]ActionItem, error) {
	rows, err := q.db.QueryContext(ctx, listPublicationActionItems, publicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActionItem
	for rows.Next() {
		var i ActionItem
		if err := rows.Scan(
			&i.ID,
			&i.ReportDefinitionID,
			&i.PublicationID,
			&i.CommentID,
			&i.Text,
			&i.OwnerID,
			&i.DueDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ClosedAt,
			&i.ClosingNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicationComments = `-- name: ListPublicationComments :many
SELECT comments.id, comments.publication_id, comments.goal_id, comments.parent_id, comments.author_id, comments.body, comments.created_at, accounts.id, accounts.email, accounts.is_admin, accounts.created_at, accounts.departed
FROM comments
JOIN accounts ON accounts.id = comments.author_id
WHERE comments.publication_id = ?
ORDER BY comments.id
`

type ListPublicationCommentsRow struct {
	Comment Comment
	Account Account
}

// A publication's comments with their authors, oldest first, so each thread
// reads in the order it was written.
func (q *Queries) ListPublicationComments(ctx context.Context, publicationID int64) ([]ListPublicationCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublicationComments, publicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicationCommentsRow
	for rows.Next() {
		var i ListPublicationCommentsRow
		if err := rows.Scan(
			&i.Comment.ID,
			&i.Comment.PublicationID,
			&i.Comment.GoalID,
			&i.Comment.ParentID,
			&i.Comment.AuthorID,
			&i.Comment.Body,
			&i.Comment.CreatedAt,
			&i.Account.ID,
			&i.Account.Email,
			&i.Account.IsAdmin,
			&i.Account.CreatedAt,
			&i.Account.Departed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadAuthors = `-- name: ListThreadAuthors :many
SELECT DISTINCT accounts.id, accounts.email, accounts.is_admin, accounts.created_at, accounts.departed
FROM comments
JOIN accounts ON accounts.id = comments.author_id
WHERE comments.id = ?1 OR comments.parent_id = ?1
ORDER BY accounts.email
`

// The distinct authors of a thread (its first comment and every reply), for
// alerting everyone in it to a new reply.
func (q *Queries) ListThreadAuthors(ctx context.Context, threadID int64) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listThreadAuthors, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.Departed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
