// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Account struct {
	ID        int64
	Email     string
	IsAdmin   int64
	CreatedAt string
	Departed  int64
	Name      *string
}

type ActionItem struct {
	ID                 int64
	ReportDefinitionID int64
	PublicationID      int64
	CommentID          int64
	Text               string
	OwnerID            int64
	DueDate            string
	CreatedBy          int64
	CreatedAt          string
	ClosedAt           string
	ClosingNote        string
}

type Checkin struct {
	ID              int64
	GoalID          int64
	AuthorID        int64
	OwnerID         int64
	Health          string
	Status          string
	PathToGreen     string
	PathTargetDate  string
	CreatedAt       string
	Explanation     string
	LifecycleFrom   string
	LifecycleTo     string
	LifecycleReason string
	Outcome         string
}

type Comment struct {
	ID            int64
	PublicationID int64
	GoalID        int64
	ParentID      int64
	AuthorID      int64
	Body          string
	CreatedAt     string
}

type Contributor struct {
	ID        int64
	GoalID    int64
	AccountID int64
	CreatedAt string
}

type DateSlip struct {
	ID          int64
	GoalID      int64
	CheckinID   int64
	MilestoneID *int64
	OldDate     string
	NewDate     string
	Reason      string
	CreatedAt   string
}

type DefinitionChange struct {
	ID          int64
	ActorID     int64
	DimensionID *int64
	FieldID     *int64
	Summary     string
	CreatedAt   string
}

type Delegate struct {
	ID        int64
	GoalID    int64
	AccountID int64
	CreatedAt string
}

type Dimension struct {
	ID        int64
	Name      string
	CreatedAt string
	Selection string
	List      string
	Retired   int64
	Required  int64
}

type DimensionValue struct {
	ID          int64
	DimensionID int64
	Value       string
	Retired     int64
	CreatedAt   string
	Position    int64
}

type Field struct {
	ID        int64
	Name      string
	Type      string
	Unit      string
	Retired   int64
	CreatedAt string
	Required  int64
}

type Goal struct {
	ID           int64
	Title        string
	SoWhat       string
	OwnerID      int64
	Lifecycle    string
	CreatedAt    string
	Kind         string
	DeliveryDate string
	CadenceDays  int64
	TopLevel     int64
	ActivatedAt  string
}

type GoalDimensionValue struct {
	ID               int64
	GoalID           int64
	DimensionValueID int64
	CreatedAt        string
}

type GoalFieldValue struct {
	GoalID    int64
	FieldID   int64
	Value     string
	UpdatedAt string
}

type GoalValueChange struct {
	ID          int64
	GoalID      int64
	ActorID     int64
	DimensionID *int64
	FieldID     *int64
	Attribute   string
	Several     int64
	BeforeValue string
	AfterValue  string
	CreatedAt   string
}

type Handoff struct {
	ID          int64
	GoalID      int64
	FromOwner   int64
	ToOwner     int64
	Status      string
	InitiatedBy int64
	CreatedAt   string
}

type Highlight struct {
	ID        int64
	CheckinID int64
	Kind      string
	Note      string
	CreatedAt string
}

type Link struct {
	ID          int64
	ChildID     int64
	ParentID    int64
	Status      string
	Note        string
	RequestedBy int64
	CreatedAt   string
}

type LinkRemoval struct {
	ID            int64
	ChildID       int64
	ParentID      int64
	Note          string
	RequestedBy   int64
	LinkCreatedAt string
	RemovedBy     int64
	RemovedAt     string
	RestoredAt    *string
}

type Metric struct {
	ID         int64
	GoalID     int64
	Name       string
	Unit       string
	Direction  string
	Baseline   float64
	Target     float64
	TargetDate string
	CreatedAt  string
}

type MetricReading struct {
	ID        int64
	CheckinID int64
	MetricID  int64
	Value     float64
	CreatedAt string
}

type Milestone struct {
	ID               int64
	GoalID           int64
	Name             string
	TargetDate       string
	CreatedAt        string
	Status           string
	RemovedReason    string
	AddedWhileActive int64
}

type MilestoneChange struct {
	ID          int64
	CheckinID   int64
	MilestoneID int64
	Kind        string
	Reason      string
	CreatedAt   string
	Name        string
}

type NarrativePick struct {
	ID                 int64
	ReportDefinitionID int64
	HighlightID        int64
	Section            string
}

type NarrativeText struct {
	ReportDefinitionID int64
	Section            string
	Text               string
}

type Nudge struct {
	ID        int64
	GoalID    int64
	SentBy    int64
	NudgedOn  string
	CreatedAt string
}

type ParentSuggestion struct {
	ID          int64
	GoalID      int64
	ParentID    int64
	SuggestedBy int64
	Note        string
	Status      string
	CreatedAt   string
	ClosedAt    *string
}

type RejectedLinkRequest struct {
	ID               int64
	ChildID          int64
	ParentID         int64
	Note             string
	RequestedBy      int64
	RequestCreatedAt string
	RejectedBy       int64
	RejectedAt       string
	RestoredAt       *string
}

type ReportDefinition struct {
	ID           int64
	Name         string
	Introduction string
	CreatedBy    int64
	CreatedAt    string
	Mode         string
}

type ReportDefinitionField struct {
	ID                 int64
	ReportDefinitionID int64
	FieldID            int64
}

type ReportDefinitionGoal struct {
	ID                 int64
	ReportDefinitionID int64
	List               string
	GoalID             int64
}

type ReportPublication struct {
	ID                 int64
	ReportDefinitionID int64
	PublishedBy        int64
	PublishedAt        string
	Snapshot           string
}

type ReportRule struct {
	ID                 int64
	ReportDefinitionID int64
	Attribute          string
	DimensionID        int64
	Op                 string
}

type ReportRuleValue struct {
	ID           int64
	ReportRuleID int64
	Value        string
}

type SoWhatRevision struct {
	ID        int64
	GoalID    int64
	SoWhat    string
	AuthorID  int64
	CreatedAt string
}

type UndoToken struct {
	ID        int64
	Token     string
	Kind      string
	SubjectID int64
	AccountID int64
	Detail    string
	IssuedAt  string
	UsedAt    *string
}
