// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Account struct {
	ID        int64
	Email     string
	IsAdmin   int64
	CreatedAt string
	Departed  int64
	Name      *string
}

type ActionItem struct {
	ID                 int64
	ReportDefinitionID int64
	PublicationID      int64
	CommentID          int64
	Text               string
	OwnerID            int64
	DueDate            string
	CreatedBy          int64
	CreatedAt          string
	ClosedAt           string
	ClosingNote        string
}

type Checkin struct {
	ID              int64
	GoalID          int64
	AuthorID        int64
	OwnerID         int64
	Health          string
	Status          string
	PathToGreen     string
	PathTargetDate  string
	CreatedAt       string
	Explanation     string
	LifecycleFrom   string
	LifecycleTo     string
	LifecycleReason string
	Outcome         string
}

type Comment struct {
	ID            int64
	PublicationID int64
	GoalID        int64
	ParentID      int64
	AuthorID      int64
	Body          string
	CreatedAt     string
}

type Contributor struct {
	ID        int64
	GoalID    int64
	AccountID int64
	CreatedAt string
}

type DateSlip struct {
	ID          int64
	GoalID      int64
	CheckinID   int64
	MilestoneID *int64
	OldDate     string
	NewDate     string
	Reason      string
	CreatedAt   string
}

type Delegate struct {
	ID        int64
	GoalID    int64
	AccountID int64
	CreatedAt string
}

type Dimension struct {
	ID        int64
	Name      string
	CreatedAt string
	Selection string
}

type DimensionValue struct {
	ID          int64
	DimensionID int64
	Value       string
	Retired     int64
	CreatedAt   string
}

type Goal struct {
	ID           int64
	Title        string
	SoWhat       string
	OwnerID      int64
	Lifecycle    string
	CreatedAt    string
	Kind         string
	DeliveryDate string
	CadenceDays  int64
	TopLevel     int64
	ActivatedAt  string
}

type GoalDimensionValue struct {
	ID               int64
	GoalID           int64
	DimensionValueID int64
	CreatedAt        string
}

type Handoff struct {
	ID          int64
	GoalID      int64
	FromOwner   int64
	ToOwner     int64
	Status      string
	InitiatedBy int64
	CreatedAt   string
}

type Highlight struct {
	ID        int64
	CheckinID int64
	Kind      string
	Note      string
	CreatedAt string
}

type Link struct {
	ID          int64
	ChildID     int64
	ParentID    int64
	Status      string
	Note        string
	RequestedBy int64
	CreatedAt   string
}

type Metric struct {
	ID         int64
	GoalID     int64
	Name       string
	Unit       string
	Direction  string
	Baseline   float64
	Target     float64
	TargetDate string
	CreatedAt  string
}

type MetricReading struct {
	ID        int64
	CheckinID int64
	MetricID  int64
	Value     float64
	CreatedAt string
}

type Milestone struct {
	ID               int64
	GoalID           int64
	Name             string
	TargetDate       string
	CreatedAt        string
	Status           string
	RemovedReason    string
	AddedWhileActive int64
}

type NarrativePick struct {
	ID                 int64
	ReportDefinitionID int64
	HighlightID        int64
	Section            string
}

type NarrativeText struct {
	ReportDefinitionID int64
	Section            string
	Text               string
}

type ReportDefinition struct {
	ID            int64
	Name          string
	Introduction  string
	Depth         int64
	OwnerFilterID int64
	CreatedBy     int64
	CreatedAt     string
}

type ReportDefinitionFilter struct {
	ID                 int64
	ReportDefinitionID int64
	DimensionValueID   int64
}

type ReportDefinitionRoot struct {
	ID                 int64
	ReportDefinitionID int64
	GoalID             int64
}

type ReportPublication struct {
	ID                 int64
	ReportDefinitionID int64
	PublishedBy        int64
	PublishedAt        string
	Snapshot           string
}

type SoWhatRevision struct {
	ID        int64
	GoalID    int64
	SoWhat    string
	AuthorID  int64
	CreatedAt string
}
