// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Account struct {
	ID        int64
	Email     string
	IsAdmin   int64
	CreatedAt string
}

type Goal struct {
	ID        int64
	Title     string
	SoWhat    string
	OwnerID   int64
	Lifecycle string
	CreatedAt string
}

type Link struct {
	ID          int64
	ChildID     int64
	ParentID    int64
	Status      string
	Note        string
	RequestedBy int64
	CreatedAt   string
}
